# Azure DevOps reusable template for autoSDLC analysis stage
# Usage: reference this template in your pipeline:
#   resources:
#     repositories:
#       - repository: templates
#         type: git
#         name: autosdlc/templates
#   stages:
#     - template: .azuredevops/pipelines/autosdlc-analyze.yml@templates

stages:
  - stage: Analyze
    displayName: 'autoSDLC Analysis'
    condition: |
      or(
        eq(variables['Build.SourceBranchName'], 'plan'),
        eq(variables['Build.SourceBranchName'], 'spec'),
        eq(variables['Build.SourceBranchName'], 'task'),
        eq(variables['Build.SourceBranchName'], 'develop')
      )
    
    jobs:
      - job: AutoSDLC_Analyze
        displayName: 'Run autoSDLC Analysis'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - script: |
              # Get Azure DevOps OIDC token (System.AccessToken)
              echo "##vso[task.setvariable variable=OIDC_TOKEN;issecret=true]$(System.AccessToken)"
            displayName: 'Get OIDC Token'

          - script: |
              docker run --rm \
                ghcr.io/autosdlc/cli:latest analyze \
                --token "$(OIDC_TOKEN)" \
                --pipeline-id "$(Build.BuildId)"
            displayName: 'Run autoSDLC Analysis'
            env:
              DOCKER_BUILDKIT: 1
