stages:
  - manage

manage:
  stage: manage
  image: docker:24-cli
  services:
    - docker:24-dind
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://autosdlc.io
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  script:
    - |
      docker run --rm \
       autosdlc/cli:latest trigger \
        --token "$GITLAB_OIDC_TOKEN" \
        --pipeline-id "$CI_PIPELINE_ID"
