stages:
  - stage: autoSDLC
    displayName: 'autoSDLC'
    condition: |
      or(
        eq(variables['Build.SourceBranchName'], 'main'),
        eq(variables['Build.SourceBranchName'], 'master')
      )
    
    jobs:
      - job: trigger
        displayName: 'autoSDLC Trigger'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              # Get Azure DevOps OIDC token (System.AccessToken)
              echo "##vso[task.setvariable variable=OIDC_TOKEN;issecret=true]$(System.AccessToken)"
            displayName: 'Get OIDC Token'

          - script: |
              docker run --rm \
                -v $(Build.SourcesDirectory):/workspace \
                -w /workspace \
                autosdlc/cli:latest trigger \
                --token "$(OIDC_TOKEN)" \
                --pipeline-id "$(Build.BuildId)"
            displayName: 'Trigger autoSDLC Pipeline'
            env:
              DOCKER_BUILDKIT: 1
